name: 'Fetch JSON and Call API'
description: 'Fetch JSON from URL and call API with the data'
inputs:
  source-url:
    description: 'URL to fetch JSON data from'
    required: true
  access-key:
    description: 'X-AccessKey for API authentication'
    required: true
  electron-key:
    description: 'electronKey parameter for API'
    required: true
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
  version:
    description: 'version'
    required: true
  prompt-upgrade-content:
    description: '升级提示信息'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-url }}
    - ${{ inputs.access-key }}
    - ${{ inputs.electron-key }}
    - ${{ inputs.github-token }}
    - ${{ inputs.version }}
    - ${{ inputs.prompt-upgrade-content }}